# Task 8: pipeline.yaml

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: npminstall
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
      runAfter:
        - tests
      params:
        - name: IMAGE
          value: us.icr.io/YOUR_NAMESPACE/tax-calculator:latest
      workspaces:
        - name: source
          workspace: pipeline-workspace
